sudo: required
language: python
python:
  - "2.6"
  - "2.7"
env: 
  - FLASK=0.10.1
install: "sudo apt-get install libmysqlclient-dev python-dev; pip install -r requirements.txt"
addons: 
  mariadb: 10.1
script: "py.test ."
