language: python
python:
  - "3.6"
services: mysql
before_install:
    sudo apt-get install libmariadbclient-dev
install: "pip install -r requirements.txt"
addons:
  mariadb: 10.1
before_script:
  - mysql -u root -e "SET GLOBAL max_connections = 1000;"
  - mysql -u root < sql/setup.sql
  - mysql -u donut_test --password=public < sql/reset.sql
script: "yapf -d -r . && make test"
